### ISSUE TITLE
Build fails for v1.10 firmware

### ISSUE THREAD

**Issue by aswild** [aswild/vyatta-wireguard-build#1]
Comment from @phillipmcmahon on https://github.com/Lochnair/vyatta-wireguard/issues/108

I installed a debian VM with all packages needed and it worked like a charm. This was primarily to test whether I had the right setup.

I am running the 1.10.9 firmware on the ER-6P (e300 platform) and wish to target that. From the firmware download, I pulled the GPL file, extracted the kernel tgz, named it correctly and dropped it in the src folder.

Ran a ./build.sh clean and then a ./build.sh which throws the following error;

/home/phillipmcmahon/vyatta-wireguard-build/src/kernel/scripts/kconfig/Makefile:105: recipe for target 'ubnt_er_e300_defconfig' failed make[1]: *** [ubnt_er_e300_defconfig] Error 1 Makefile:506: recipe for target 'ubnt_er_e300_defconfig' failed make: *** [ubnt_er_e300_defconfig] Error 2

After looking through your build.sh I am unsure where to go next. Any pointers would be appreciated.

**Comment by aswild** [comment]
Hi Phillip,
Moving the discussion here to avoid cluttering Lochnair's repo issues.

The ubnt_er_<board>_defconfig files in the kernel are new for firmware v2, in 1.10.x I'm pretty sure the config is just saved as the top-level `.config` in the kernel tarball.

Should be fixable by just commenting out `run make ubnt_er_${ER_BOARD}_defconfig` in build.sh

**Comment by phillipmcmahon** [comment]
Appreciate the response.

Commenting out that line does indeed get me further than before. However, seems compiling wireguard is now the issue. Apologies for the hand holding requests, pretty new at this compile type stuff.

`~/vyatta-wireguard-build
>>> Build WireGuard kernel module <<<
+ make -C /home/phillipmcmahon/vyatta-wireguard-build/src/kernel M=/home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src modules
make: Entering directory '/home/phillipmcmahon/vyatta-wireguard-build/src/kernel'

  WARNING: Symbol version dump /home/phillipmcmahon/vyatta-wireguard-build/src/kernel/Module.symvers
           is missing; modules will have no dependencies and modversions.

  CC [M]  /home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src/main.o
In file included from <command-line>:0:0:
/home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src/compat/compat.h:219:19: error: redefinition of 'prandom_u32_max'
In file included from include/linux/net.h:22:0,
                 from include/linux/skbuff.h:27,
                 from include/linux/ip.h:20,
                 from include/linux/if_tunnel.h:4,
                 from include/net/ip_tunnels.h:4,
                 from /home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src/compat/compat.h:90,
                 from <command-line>:0:
include/linux/random.h:48:19: note: previous definition of 'prandom_u32_max' was here
scripts/Makefile.build:308: recipe for target '/home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src/main.o' failed
make[1]: *** [/home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src/main.o] Error 1
Makefile:1296: recipe for target '_module_/home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src' failed
make: *** [_module_/home/phillipmcmahon/vyatta-wireguard-build/src/WireGuard/src] Error 2
make: Leaving directory '/home/phillipmcmahon/vyatta-wireguard-build/src/kernel'`

**Comment by aswild** [comment]
Oh yeah, Wireguard's compat.h thinks prandom_u32_max needs to be backported, but the e300 kernel included it. Rename or delete that function in compat.h and it should build. I used to do that in my old build script https://gist.github.com/aswild/41d53a612e15e3561e9ba039a95c3f1d#file-vyatta_wireguard_build-sh-L131

Careful, running build.sh will clean by default, so either disable that or patch wireguard in the prepare function.

Also, thanks for being a guinea pig for this :) When I have time I'll incorporate all these fixes, probably on a separate v1.0 branch.

**Comment by phillipmcmahon** [comment]
Added in the sed command in the prepare stage.
Get me almost to the end...

>>> Build deb package <<<
+ install -m644 /home/phillipmcmahon/vyatta-wireguard-build/wireguard.ko e300/lib/modules/3.10.107-UBNT/kernel/net/
install: target 'e300/lib/modules/3.10.107-UBNT/kernel/net/' is not a directory: No such file or directory

I changed the kernel value to 3.10.107-UBNT in build.sh and also in the .gitmodules I changed from v2.0 to master.

However each time the v2 kernel is pulled and I replace/delete with my local v.1.10.9 version. Clearly this is wrong but not sure where to change it.

Apologies for the spoon feeding nature of my question. :/

**Comment by phillipmcmahon** [comment]
Total kludge. I ended up creating the dir structure manually and doing this in build.sh

`prepare_package() {
    pushd "$SRCDIR/vyatta-wireguard"
    #msg "Clean deb package"
    #run git reset --hard
    #run git clean -dxfq
    popd
}`

It _works_ but I feel dirty...

Now to test the package it made and hope I don't brick my router :0)

**Comment by aswild** [comment]
You were on the right track with changing the branch of vyatta-wireguard, but just editing .gitmodules won't do what's needed.

cd into the vyatta-wireguard directory and do a `git checkout master` there. Then cd back to the top level and you may need to commit the vyatta-wireguard directory (or have build.sh skip the `git submodule update --init` step).

The branch field in .gitmodules is only used for certain commands like `git submodule update --remote` which pulls the latest upstream commit of the submodule, editing it doesn't change the SHA that's remembered in the parent repo.

**Comment by phillipmcmahon** [comment]
So I deleted the dir, cloned from scratch.

cd'ed into the vyatta-wireguard dir and performed a git checkout master. Told me I was already on master.

Made the following changes to build.sh;

Changed;
ER_KERNEL_RELEASE="3.10.107-UBNT"

Commented out
run make ubnt_er_${ER_BOARD}_defconfig

Added this line at the end (before popd) of prepare_wireguard()
run sed -i 's/prandom_u32_max/\0_exclude_for_e300/' src/compat/compat.h

Still pulls the v2 kernel zip and I get the same dir error when the package is building.

What final changes are needed here to avoid the kludge of;

1) Adding the 3.10.107 kernel file directly
2) Adding the 3.10.107-UBNT lib path manually
2) Commenting out prepare_package() so it is just a stub function

Thanks again in advance.

**Comment by aswild** [comment]
There's a couple ways to add proper v1.x support, I'm still not sure which to go with.

Option1: Add FW v1 and v2 support to the master branch of this repo, that includes the v1.x kernel sources and v1.x of vyatta-wireguard (either another submodule, or have build.sh do a "git checkout" there for the correct branch).

Option 2: Split this repo into 1.x and 2.x branches, which reference the correct rev of vyatta-wireguard in the submodule config.

I'm kinda leaning towards option 1 so I don't have to maintain two branches here

**Comment by aswild** [comment]
OK, I got some v1.10.x support added here, run `./build.sh v1` to build the e300 package for the old firmware branch.

There's 2 copies of the vyatta-wireguard submodule, since that plays a little nicer than running "git checkout" inside a submodule, but unfortunately that means git downloads 2 full clones of the vyatta-wireguard repo, oh well.

Also I dropped Git LFS because this repo totally blew my Github LFS bandwidth quota I didn't know existed. I threw the toolchain and kernel tarballs into an S3 bucket instead, which is way cheaper than extra Github storage.

I can't really test the v1 packages, but it looks like it built correctly, let me know how it goes.

**Comment by phillipmcmahon** [comment]
Legend.

I'll test tonight once I'm back from work.

**Comment by phillipmcmahon** [comment]
Works like a charm - sorry for the delay in getting back to you.

I saw an updated version has been pushed to the wireguard repository, v0.0.20190702. Does the script need editing to pick this up?

**Comment by aswild** [comment]
Excellent, glad to hear it works!

I'll update to 20190702 when I get a chance, but theoretically all it should take is changing the WireGuard submodule revision
